import { createAction } from "@reduxjs/toolkit";

export const createNewMap = createAction("createNewMap");
export const loadMap = createAction("loadMap");
export const setMapName = createAction("setMapName");
export const setToolbarTab = createAction("setToolbarTab");
export const setTool = createAction("setTool");
export const setZoomLevel = createAction("setZoomLevel");
export const setTileSize = createAction("setTileSize");
export const completeFeature = createAction("completeFeature");
export const focusFeature = createAction("focusFeature");
export const updateFeature = createAction("updateFeature");
export const printAreaStarted = createAction("printAreaStarted");
export const removeFeature = createAction("removeFeature");
export const highlightFeature = createAction("highlightFeature");
export const setGeometry = createAction("setGeometry");
export const createJob = createAction("createJob");
export const destoryJob = createAction("destoryJob");
export const startJob = createAction("startJob");
export const setRemainingTiles = createAction("setRemainingTiles");
export const finishJob = createAction("finishJob");
